"""Video editing adapters."""

from .ffmpeg_finalizer import (
    AudioTrack,
    FinalizerError,
    FinalMergeSpec,
    build_final_merge_command,
    default_final_merge_spec,
    inspect_final_output,
    load_finalizer_config,
    run_final_merge,
    run_standard_final_merge,
    validate_standard_metadata,
    validate_standard_output,
)
from .video_use import (
    VIDEO_USE_CAPABILITIES,
    VideoUseError,
    build_edit_plan,
    build_self_eval_plan,
    load_video_use_config,
    probe_source,
    render_command,
    validate_edl,
    verify_video_use_installation,
    video_use_environment,
)

__all__ = [
    "AudioTrack",
    "FinalizerError",
    "FinalMergeSpec",
    "VIDEO_USE_CAPABILITIES",
    "VideoUseError",
    "build_edit_plan",
    "build_final_merge_command",
    "default_final_merge_spec",
    "build_self_eval_plan",
    "load_video_use_config",
    "load_finalizer_config",
    "inspect_final_output",
    "probe_source",
    "render_command",
    "run_final_merge",
    "run_standard_final_merge",
    "validate_standard_metadata",
    "validate_standard_output",
    "validate_edl",
    "verify_video_use_installation",
    "video_use_environment",
]
